import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import ParkCards from '../components/ParkCards'
import Footer from '../components/Footer'
import styles from '../styles/home.module.scss'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AirTank interview project - Brent Danley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Hero />
        <ParkCards />
        <Footer />
      </main>
    </div>
  )
}

export default Home